In [1]:
import numpy as np

A matrix is in row-reduced form if it satisfies the following four conditions:
- (i) All zero rows appear below nonzero rows when both
types are present in the matrix.
- (ii) The first nonzero element in any nonzero row is 1.
- (iii) All elements directly below (that is, in the same column
but in succeeding rows from) the first nonzero element
of a nonzero row are zero.
- (iv) The first nonzero element of any nonzero row appears
in a later column (further to the right) than the first
nonzero element in any preceding row. "


Raw Reduced Echelon Form
- Satisfies all the conditions of REF.
- Each leading 1 is the only non-zero entry in its column, meaning that there are zeros above and below each leading 112

#### QUESTION

In [2]:
# For the below efined matrix find raw reduced echlon form
# Please note that belowe matrix is not defined via numpy array

from sympy import Matrix


A = Matrix([
  [5, 6, 7],
  [11, 23, 22],
  [12, 21, 31]
])

- We can make use of .rref() method from sympy to find raw reduced echlon form
- The Matrix().rref() method in SymPy puts a matrix into reduced row echelon form (RREF) and returns a tuple of two elements:
    - The first element is the reduced row echelon form
    - The second element is a tuple of indices of the pivot columns 


In [3]:
raw_reduced_form, pivot_raws = A.rref()

In [4]:
raw_reduced_form

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [5]:
# Indices of pivot columns
pivot_raws

(0, 1, 2)

### We can usw .rref() for matrices defined like above, that is matrices defined via Matrixy 
### .rref() can't use in nump.array()

In [6]:
# This will produce an error
A = np.array([
  [5, 6, 7],
  [11, 23, 22],
  [12, 21, 31]
])
raw_reduced_form, pivot_raws = A.rref()

AttributeError: 'numpy.ndarray' object has no attribute 'rref'

#### QUESTION
Without using .rref() write code to find raw reduced form of a matrix. 

In [8]:
# Normalise the raws
def raw_reduced(A):

    # Convert A to a floating-point data type to perform devision properly
    A = A.astype(float)  
    m = A.shape[0]         # Number of raws
    n = A.shape[1]        # Number of columns


    # The following will find first non zero entry in first column also raw number of first non zero entry
    i = 0
    while A[i,0] ==0:
        i += 1
    
    p = A[i,0]               # Set first non-zero element in the raw
    for j in range(0,n):  
        A[i,j] = A[i,j]/p    # Divide each element in the raw with first non zero element
    
    
    if i != m-1:            # Do this only if the non zero raw is not last raw
        for k in range(i+1,m):               # Moving to next raw
            q = A[k,0] # Fixing non zero entry of the raw
            for j in range(0,n):
                A[k,j] = A[k,j] - (q*A[i,j])
            
    return A

In [9]:
# Interchange the raws
def interchange_raws(A):
    i = 0             # Jus to show we are working with first column
    if A[0,0] != 1:    # Interchange only if the first element is not one 
        for k in range(3):    # Find index of raw with element 1
            if A[k, 0] != 0:
                A[[0, k]] = A[[k, 0]]
                return A
                break 
                
    else:
        return A

In [10]:
# Main function Edited

def function_2(A):
    i = 0

    if any(A[j,0] != 0 for j in range(0,3)):  # Let us try with 3 raws
        B = raw_reduced(A)  # Normalise
        C = interchange_raws(B) # Interchange
        return C
    else:
        None

In [11]:
A = np.array([
  [0,5,  7],
  [0,0, 23],
  [0,4,13]
])

print(function_2(A))

None


In [12]:
A = np.array([
  [21,5,  7],
  [0,0, 23],
  [0,4,13]
])

print(function_2(A))

[[ 1.          0.23809524  0.33333333]
 [ 0.          0.         23.        ]
 [ 0.          4.         13.        ]]


In [13]:
A = np.array([
  [21,5,  7],
  [42,0, 23],
  [0,4,13]
])

print(function_2(A))

[[  1.           0.23809524   0.33333333]
 [  0.         -10.           9.        ]
 [  0.           4.          13.        ]]


In [14]:
A = np.array([
  [21,5,  7],
  [42,0, 23],
  [63,4,13]
])

print(function_2(A))

[[  1.           0.23809524   0.33333333]
 [  0.         -10.           9.        ]
 [  0.         -11.          -8.        ]]


In [15]:
A = np.array([
  [0,5,  10],
  [5,10, 50],
  [20,400,130]
])

print(function_2(A))

[[  1.   2.  10.]
 [  0.   5.  10.]
 [  0. 360. -70.]]


In [16]:
A = np.array([
  [0,5,  10],
  [0,10, 50],
  [20,400,130]
])

print(function_2(A))

[[ 1.  20.   6.5]
 [ 0.  10.  50. ]
 [ 0.   5.  10. ]]


- We have done with first column. 
- Now we need to move to second column but not all elements but the inside square matrix


- Let us try to generalise above two functions (raw-reduced) and (interchange_raw) 

### The below function works well, both normalisation of raws and interchange of raws,

### The problem is this fails when last entry become zero in the last stept

In [17]:
def normalised(A):
    A = A.astype(float)
    m = A.shape[0]  # Number of rows
    n = A.shape[1]  # Number of columns
    
    # raw reduced form upto second last column
    for i in range(0,n-1): 
        c = i              # Fixing column number
        j = i              # Initialise raw number
        while  j< m and A[j,c] ==0:
            j += 1
        p = A[j,c]         # Fixing the non zer entry
        
        # Divide corresponding raw with non zer entry p 
        for k in range(c,n): # Avoiding raws before that columns
            A[j,k] = A[j,k]/p
        
        # Make Changes to raws below the 
        if j != m-1:
            for k in range(j+1,m):
                q = A[k,c] # Fixing first non zero entry in the raw
                for r in range(c,n):
                    A[k,r] = A[k,r] - (q*A[j,r])
                    
         # Now interchange the raws
        if A[i,i] != 1:         #Interchange only if the first element is not one
            for k in range(i,m):
                if A[k,i] !=0:
                    A[[i,k]] = A[[k,i]]
                    break
    
    # Raw reduced form for the last column
    return A

In [18]:
A = np.array([[0,1,3],[0,0,6],[1,3,0]])
print(A)

print(normalised(A))

[[0 1 3]
 [0 0 6]
 [1 3 0]]
[[1. 3. 0.]
 [0. 1. 3.]
 [0. 0. 6.]]


In [19]:
A = np.array([[2,1,3],[0,0,6],[4,0,6]])
print(A)

print(normalised(A))

[[2 1 3]
 [0 0 6]
 [4 0 6]]
[[ 1.   0.5  1.5]
 [ 0.   1.  -0. ]
 [ 0.   0.   6. ]]


In [20]:
A = np.array([[2,1,3],[0,6,6],[0,6,6]])
print(A)

print(normalised(A))

[[2 1 3]
 [0 6 6]
 [0 6 6]]
[[1.  0.5 1.5]
 [0.  1.  1. ]
 [0.  0.  0. ]]


In [21]:
# There is a problem, may be with last column

In [22]:
A = np.array([[2,1,3],[0,6,6],[0,6,0]])
print(A)

print(normalised(A))

[[2 1 3]
 [0 6 6]
 [0 6 0]]
[[ 1.   0.5  1.5]
 [ 0.   1.   1. ]
 [ 0.   0.  -6. ]]


In [23]:
A = np.array([[2,1,3],[0,6,6],[0,4,0]])
print(A)

print(normalised(A))

[[2 1 3]
 [0 6 6]
 [0 4 0]]
[[ 1.   0.5  1.5]
 [ 0.   1.   1. ]
 [ 0.   0.  -4. ]]


In [24]:
# Below we add if j ==m: continue for the continuity of for looop for 

In [5]:
def normalised(A):
    A = A.astype(float)
    m = A.shape[0]  # Number of rows
    n = A.shape[1]  # Number of columns
    
    # We iterate through each column 
    
    # Raw reduced form upto last column
    for i in range(0,n):
        c = i              # Fixing column number
        j = i              # Initialise raw number
        while  j< m and A[j,c] ==0:
            j += 1

                
        if j ==m:
            continue       # Move to next value of i if j becomes m. More than the number of raws
       
        
        p = A[j,c]         # Fixing the non zer entry
        
        # Divide corresponding raw with non zer entry p 
        for k in range(c,n): # Avoiding raws before that columns
            A[j,k] = A[j,k]/p
        
        # Make Changes to raws below the 
        if j != m-1:
            for k in range(j+1,m):
                q = A[k,c] # Fixing first non zero entry in the raw
                for r in range(c,n):
                    A[k,r] = A[k,r] - (q*A[j,r])
                    
         # Now interchange the raws
        if A[i,i] != 1:         #Interchange only if the first element is not one
            for k in range(i,m):
                if A[k,i] !=0:
                    A[[i,k]] = A[[k,i]]
                    break
    return A

In [6]:
A = np.array([[2,1,3,5],[0,6,6,2],[0,6,6,6],[0,6,6,6]])
print(A)

print(normalised(A))

[[2 1 3 5]
 [0 6 6 2]
 [0 6 6 6]
 [0 6 6 6]]
[[1.         0.5        1.5        2.5       ]
 [0.         1.         1.         0.33333333]
 [0.         0.         0.         4.        ]
 [0.         0.         0.         1.        ]]


In [ ]:
# Now we need to ensure all the entries below the first non zero entry of each column is 0 

- Find first non zero entry of the column. 
- If it is not 1 divide with the same element.
- Relace all values below the with 0

In [7]:
# Let us make changes in the function normalised

def normalised(A):
    A = A.astype(float)
    m = A.shape[0]  # Number of rows
    n = A.shape[1]  # Number of columns
    
    # We iterate through each column 
    
    # Raw reduced form upto last column
    for i in range(0,n):
        c = i              # Fixing column number
        j = i              # Initialise raw number
        while  j< m and A[j,c] ==0:
            j += 1

                
        if j ==m:
            continue       # Move to next value of i if j becomes m. More than the number of raws
       
        
        p = A[j,c]         # Fixing the non zer entry
        
        # Divide corresponding raw with non zer entry p 
        for k in range(c,n): # Avoiding raws before that columns
            A[j,k] = A[j,k]/p
        
        # Make Changes to raws below the 
        if j != m-1:
            for k in range(j+1,m):
                q = A[k,c] # Fixing first non zero entry in the raw
                for r in range(c,n):
                    A[k,r] = A[k,r] - (q*A[j,r])
                    
         # Now interchange the raws
        if A[i,i] != 1:         #Interchange only if the first element is not one
            for k in range(i,m):
                if A[k,i] !=0:
                    A[[i,k]] = A[[k,i]]
                    break
         
    for j in range(m):
        
        i = 0
        while i < n and A[j,i] ==0:   # Search for first non zero entry
            i += 1
            
        if i == n:
            continue
         
        A[j,i] = A[j,i]/A[j,i]     # Making non zero entry 1
        
        
        # Set all entries below 1 as zero
        for l in range(j+1,m):
            A[l,i] = 0
                    
    return A

In [10]:
A = np.array([[2,1,3,5],[0,6,6,2],[0,6,6,6],[0,6,6,6]])
print(A)

print(normalised(A))

[[2 1 3 5]
 [0 6 6 2]
 [0 6 6 6]
 [0 6 6 6]]
[[1.         0.5        1.5        2.5       ]
 [0.         1.         1.         0.33333333]
 [0.         0.         0.         1.        ]
 [0.         0.         0.         0.        ]]


In [11]:
A = np.array([[0,2,0,0,0],[0,0,0,0,2],[0,0,0,0,0],[0,0,1,0,0],[0,0,0,0,1]])
print(A)

print(normalised(A))

[[0 2 0 0 0]
 [0 0 0 0 2]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
# We need more rearrangement