### Finding the Row Reduced Echelon Form (RREF) of a Matrix Using the SymPy Module
To compute the row reduced echelon form (RREF) of a matrix, we can utilize the sympy module. It is also possible to convert a NumPy array into a SymPy matrix and then apply the .rref() function to find the RREF.

Additionally, we have developed a custom function that computes the RREF directly, without relying on the .rref() method from SymPy.

In [1]:
import numpy as np

A matrix is in row-reduced form if it satisfies the following four conditions:
- (i) All zero rows appear below nonzero rows when both
types are present in the matrix.
- (ii) The first nonzero element in any nonzero row is 1.
- (iii) All elements directly below (that is, in the same column
but in succeeding rows from) the first nonzero element
of a nonzero row are zero.
- (iv) The first nonzero element of any nonzero row appears
in a later column (further to the right) than the first
nonzero element in any preceding row. "


Raw Reduced Echelon Form
- Satisfies all the conditions of REF.
- Each leading 1 is the only non-zero entry in its column, meaning that there are zeros above and below each leading 112

#### QUESTION

In [14]:
# For the below efined matrix find raw reduced echlon form
# Please note that belowe matrix is not defined via numpy array

from sympy import Matrix


A = Matrix([
  [5, 6, 7],
  [11, 23, 22],
  [12, 21, 31]
])

- We can make use of .rref() method from sympy to find raw reduced echlon form
- The Matrix().rref() method in SymPy puts a matrix into reduced row echelon form (RREF) and returns a tuple of two elements:
    - The first element is the reduced row echelon form
    - The second element is a tuple of indices of the pivot columns 


In [15]:
raw_reduced_form, pivot_raws = A.rref()

In [16]:
raw_reduced_form

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [17]:
# Indices of pivot columns
pivot_raws

(0, 1, 2)

### We can usw .rref() for matrices defined like above, that is matrices defined via Matrixy 
### .rref() can't use in nump.array()

In [18]:
# This will produce an error
A = np.array([
  [5, 6, 7],
  [11, 23, 22],
  [12, 21, 31]
])
raw_reduced_form, pivot_raws = A.rref()

AttributeError: 'numpy.ndarray' object has no attribute 'rref'

### We can convert numpy n dimentionale array to sympy matrix and then use the .rref

In [20]:

A = np.array([[1, 2, 1], [2, 4, 0], [3, 6, 1]])
sympy_matrix = Matrix(A)
raw_reduced_form, pivot_raws = sympy_matrix.rref()

print(raw_reduced_form)
print(pivot_raws)

Matrix([[1, 2, 0], [0, 0, 1], [0, 0, 0]])
(0, 2)


----------
-----------

## A custom function that computes raw reuduced echlon form of any matrix also gives the rank of the matrix

#### QUESTION
Without using .rref() write code to find raw reduced form of a matrix. 

### Answer
- The following will give the rank of the marrix and thr Raw Reduced Echlon form of the matrix

In [22]:
def normalised(A):
    """ This will take any matrix as out put and gives its raw reduced form and the rank of the matrix
    """
    # Print the given matrix in the out put
    print("Matrix is:")
    print(A)
    
    A = A.astype(float)
    m = A.shape[0]  # Number of rows
    n = A.shape[1]  # Number of columns
    
    # We iterate through each column 
    
    # Raw reduced form upto last column
    for i in range(0,n):
        c = i              # Fixing column number
        j = i              # Initialise raw number
        
        # If all columnelement are zero we move to next column
        
        all_zeros = all(A[j, i] == 0 for j in range(i, m))
        if all_zeros:
            continue  
        
        
        while  j< m and A[j,c] ==0:
            j += 1

        if j ==m:
            continue       # Move to next value of i if j becomes m. More than the number of raws        
        
       
        
        p = A[j,c]         # Fixing the non zero entry
        
        
        
        # Divide corresponding raw with non zero entry p 
        for k in range(c,n): # Avoiding raws before that columns
            A[j,k] = A[j,k]/p
    
        # Make Changes to raws below the 
        if j != m-1:
            for k in range(j+1,m):
                q = A[k,c] # Fixing first non zero entry in the raw
                for r in range(c,n):
                    A[k,r] = A[k,r] - (q*A[j,r])
        
        
        
        
        # Now interchange the raws
        if A[i,i] != 1:         #Interchange only if the first element is not one
            for k in range(i,m):
                if A[k,i] !=0:
                    A[[i,k]] = A[[k,i]]
                    break
    
    
    
    
    
    # To make first non zero entry 1 and below elements as 0
    for j in range(m):
        
        i = 0
        while i < n and A[j,i] ==0:   # Search for first non zero entry
            i += 1
            
        if i == n:
            continue
         
        A[j,i] = A[j,i]/A[j,i]     # Making non zero entry 1
        
        
        # Set all entries below 1 as zero
        for l in range(j+1,m):
            A[l,i] = 0
            
    
    # Final Interchange 
    # We will find indices of first non zero entry in each raw
    # We break matrix with all zero element and matrix with some non zero element
    # We rearrange matrix with some non zero according to the index
    # Then we use vstack to combine this matrix with zero matrix 
    
    
    
    
    
    # Find the indices of the first non-zero entry in each row
    indices = (A != 0).argmax(axis=1)
    
    # Store the row number and corresponding index in a list of tuples
    row_index_pairs = [(row, index) if A[row, index] != 0 else (row, -1) for row, index in enumerate(indices)]


    # Split the matrix based on row_index_pairs
    rows_with_nonzero = [A[row] for row, index in row_index_pairs if index != -1]
    rows_with_all_zero = [A[row] for row, index in row_index_pairs if index == -1]

    # Convert lists to numpy arrays
    matrix_with_nonzero = np.array(rows_with_nonzero)
    matrix_with_all_zero = np.array(rows_with_all_zero)
    

    
    # Rearrange Non Zero Matrix
    # Find the column indices of the leading pivots
    pivot_indices = [np.argmax(row != 0) for row in matrix_with_nonzero ]
    
    # Sort rows based on pivot indices
    sorted_indices = np.argsort(pivot_indices)
    rearranged_non_zero_matrix = matrix_with_nonzero[sorted_indices]
    

    if matrix_with_all_zero.size>0:
        print("Rank Of the Matrix = ", rearranged_non_zero_matrix.shape[0] )
        combined_matrix = np.vstack((rearranged_non_zero_matrix, matrix_with_all_zero))
        
        
    else:
        print("Rank of the Matrix is ", m)
        combined_matrix = rearranged_non_zero_matrix
    
    
    print("Raw Reduced Echlon form is")
    return combined_matrix

In [23]:
A = np.array([[0,2,0,0,0],[0,0,0,0,2],[0,0,0,0,0],[0,0,1,0,0],[0,0,0,0,1]])


print(normalised(A))

Matrix is:
[[0 2 0 0 0]
 [0 0 0 0 2]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]
Rank Of the Matrix =  3
Raw Reduced Echlon form is
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
A = np.array([[1,2,0,0,0],[0,0,0,0,2],[0,0,0,0,0],[0,0,1,0,0],[0,0,0,0,1]])
print(A)

print(normalised(A))

[[1 2 0 0 0]
 [0 0 0 0 2]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]
Matrix is:
[[1 2 0 0 0]
 [0 0 0 0 2]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]
Rank Of the Matrix =  3
Raw Reduced Echlon form is
[[1. 2. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
A = np.array([[0,0,0,0,0],[0,0,0,0,2],[0,0,0,0,0],[0,0,1,0,0],[0,0,0,0,1]])


print(normalised(A))

Matrix is:
[[0 0 0 0 0]
 [0 0 0 0 2]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]
Rank Of the Matrix =  2
Raw Reduced Echlon form is
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
A = np.array([[1,2,0],[0,0,2],[0,0,0],[0,0,1],[0,0,0]])


print(normalised(A))

Matrix is:
[[1 2 0]
 [0 0 2]
 [0 0 0]
 [0 0 1]
 [0 0 0]]
Rank Of the Matrix =  2
Raw Reduced Echlon form is
[[1. 2. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
A = np.array([[1,2,0],[0,0,0],[0,0,1],[0,0,0],[0,0,2]])

print(normalised(A))

Matrix is:
[[1 2 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 2]]
Rank Of the Matrix =  2
Raw Reduced Echlon form is
[[1. 2. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
# Create a 10x10 matrix of random numbers between 0 and 1
matrix = np.random.rand(10, 10)
print(normalised(matrix))

Matrix is:
[[6.83880968e-01 6.95565569e-01 4.36363802e-01 9.72616530e-01
  9.74563964e-01 8.56700824e-01 4.81258751e-01 3.18068878e-01
  7.67453064e-01 7.26152973e-01]
 [3.62519959e-01 3.88459769e-01 5.24490161e-01 2.97221060e-01
  4.80239891e-01 8.05112434e-01 8.40119145e-01 5.23519967e-01
  8.62246161e-01 1.55572829e-04]
 [5.32701086e-01 9.18242361e-01 8.34335834e-01 5.36666066e-01
  4.04239300e-01 1.16933167e-01 5.66844356e-01 5.04809609e-01
  7.88354399e-01 4.01829040e-01]
 [7.54890677e-01 9.30125558e-01 1.20948839e-01 6.64010885e-01
  6.32604357e-01 8.03459514e-01 1.40472272e-01 5.09319248e-01
  5.64579239e-01 3.64498699e-02]
 [8.11901970e-01 4.35364212e-02 6.47994867e-01 1.26202254e-02
  8.67239033e-01 9.35172473e-01 7.98154876e-02 8.42014389e-01
  9.10148336e-01 4.28537966e-01]
 [2.23963685e-01 4.26217871e-01 7.98729445e-02 6.17644955e-01
  9.00174511e-01 2.71946059e-01 2.41313189e-01 6.91456918e-01
  8.60200588e-01 5.58100063e-01]
 [6.91263628e-01 9.13022059e-01 8.32461631e-01 