In [1]:
import numpy as np

#### We can make use of numpy.linalg.solve(a,b)

A must be square and of full-rank, i.e., all rows (or, equivalently, columns) must be linearly independent; if either is not true, use lstsq for the least-squares best “solution” of the system/equation.


#### Alternatively, we can use numpy.linalg.lstsq(a, b) to solve a given system of equations.

This method generates a least squares solution for the system. If the matrix a is of full rank, it will produce the same solution as numpy.linalg.solve(a, b)

A least-squares solution solves the equation Ax = b as closely as possible, in the sense that the sum of the squares of the difference b − Ax is minimized.

### QUESTION

To solve system of equation
$$ x +2y + z = 3 $$
$$ 2x +3y - z = -6 $$
$$ 3x -2y +4z = -2$$

$ AX = B$

 $ A = \\
 [1,2,1] \\
      [2,3,-1]\\
      [3,-2,4] $

$ B = [3,-6,-2] $

### ANSWER

In [2]:
A = np.array([[1,2,1],[2,3,-1],[3,-2,-4]])

In [3]:
B = np.array([3,-6,-2])

In [4]:
X = np.linalg.solve(A,B)
print(X)

[ 4. -3.  5.]


So x = 4, y = -3 and z = 5

In [6]:
# Let us use least square method
x, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)

print(x)
print(residuals)
print(rank)
print(s)

[ 4. -3.  5.]
[]
3
[5.5206571  4.24210011 0.72590073]


### QUESTION 
Solve $$ x +3y =4 $$
$$ 2x - y = 1$$
$$ 3x + 2y = 5 $$
$$ 5x + 15 y = 20 $$

In [7]:
A = np.array([[1,3],[2,-1],[3,2],[5,15]])
B = np.array([4,1,5,20])

In [8]:
# Since A is not square, we solve using least-squares
x, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)

print(x)
print(residuals)
print(rank)
print(s)

[1. 1.]
[2.62086076e-29]
2
[16.38051603  3.11106006]


x = 1, y = 1

In [11]:
X

(array([1., 1.]),
 array([2.62086076e-29]),
 2,
 array([16.38051603,  3.11106006]))

### QUESTION 
Solve the system in variables x, y,z and q 
$$ 2z + 3q = 0 $$
$$ x + 3z + q = 0 $$
$$ x + y + 2z = 0 $$

In [23]:
A = np.array([[0,0,2,3],
              [1,0,3,1],
              [1,1,2,0]
             ])
B = np.array([0,0,0])

In [24]:
x, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)

print(x)
print(residuals)
print(rank)
print(s)

[0. 0. 0. 0.]
[]
3
[4.93005909 2.27939369 0.70631562]


This is because of rank 3 less than number of variables 4, so infinite solution

In [21]:
# To develop a inbuild function to solve system of linear equations

In [20]:
import numpy as np

# Coefficient matrix A
A = np.array([[4, 3, -5],
              [-2, -4, 5],
              [8, 8, 0]])

# Column vector of constants y
y = np.array([2, 5, -3])

# Solve the system
x = np.linalg.solve(A, y)

print("Solution vector x:")
print(x)


print(normalised(A))


Solution vector x:
[ 2.20833333 -2.58333333 -0.18333333]
Matrix is:
[[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]
Rank of the Matrix is  3
Raw Reduced Echlon form is
[[ 1.    0.75 -1.25]
 [ 0.    1.   -1.  ]
 [ 0.    0.    1.  ]]


In [ ]:
A = np.array([[4, 3, -5],
              [-2, -4, 5],
              [8, 8, 0]])